# Generated by Django 3.2.6 on 2021-09-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
