# Generated by Django 3.2.6 on 2021-09-01 15:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_memory_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
